retargeting:
  type: position
  urdf_path: shadow_hand/shadow_hand_left.urdf

  target_joint_names: null
  target_link_names: [ "thtip", "fftip", "mftip", "rftip", "lftip",
                       "thmiddle", "ffmiddle", "mfmiddle", "rfmiddle", "lfmiddle" ]

  target_link_human_indices: [ 4, 8, 12, 16, 20, 2, 6, 10, 14, 18 ]
  add_dummy_free_joint: True

  # A smaller alpha means stronger filtering, i.e. more smooth but also larger latency
  # 1 means no filter while 0 means not moving
  low_pass_alpha: 1
